In [10]:
#Write a function so that the columns of the output matrix are powers of the input
#vector.
#The order of the powers is determined by the increasing boolean argument. Specifically, when
#increasing is False, the i-th output column is the input vector raised element-wise to the power
#of N - i - 1.

import numpy as np

def vandermonde_matrix(V,N,increasing=False):
    if not increasing:
        output = np.array([ele** (N-i-1) for ele in V for i in range(N)]).reshape(V.size,N)
    elif increasing:
        output = np.array([ele** i for ele in V for i in range(N)]).reshape(V.size,N)
    return output

In [11]:
input_vector=[1,2,3]
input_vector=np.array(input_vector)
matrix = vandermonde_matrix(input_vector,3,True)
print(matrix)

[[1 1 1]
 [1 2 4]
 [1 3 9]]


In [12]:
input_vector=[1,2,3]
input_vector=np.array(input_vector)
matrix = vandermonde_matrix(input_vector,3)
print(matrix)

[[1 1 1]
 [4 2 1]
 [9 3 1]]


In [1]:
#Write a function to find moving average in an array over a window:
 #Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
import numpy as np   

In [11]:
arr=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
#arr=[10,20,30,40,50,60,70,80,90,100]

window_size=4
length_of_arr=len(arr)
#print(length_of_arr)
for i in range(0,length_of_arr-window_size+1):
    avg=np.mean(arr[i:i+4])
    print("y{} = {}".format((i+1),avg))

y1 = 4.25
y2 = 5.5
y3 = 6.75
y4 = 7.75
y5 = 23.5
y6 = 39.5
y7 = 57.25
y8 = 79.25
y9 = 88.0
y10 = 107.5
